### ISSUE TITLE
Plugin that shows Jolt ratings on Jellyfin

### ISSUE THREAD

**Issue by Tiagoez** [Dan6erbond/jolt#17]
When viewing media in Jellyfin, add user profile pictures displayed with ratings alongside, with their respective reviews.

**Comment by Dan6erbond** [comment]
I like the idea, and hope to see this plugin one day, but at the moment writing plugins for Jellyfin isn't on my roadmap. It might become a separate project, and since Jolt is technically supposed to be decoupled from Jellyfin, a different repo.
