### ISSUE TITLE
FEATURE: Databases

### ISSUE THREAD

**Issue by aleksasiriski** [Dan6erbond/jolt#3]
Please don't end up like like Jellyfin or Jellyseerr (Overseerr) saying "sqlite is enough" and buiding upon only that. From the get go start decoupling the SQL from your code and making a module for SQLite and Postgres for example, if this takes on in the future you and people using it will be sooo much happier.

I've done it in Go here: https://github.com/aleksasiriski/rffmpeg-go/tree/main/processor

**Comment by Dan6erbond** [comment]
I agree, I run a home Kubernetes cluster and SQLite is a huge PITA. This is why Jolt is built from the ground-up with Postgres as a first-class citizen. I currently use GORM to 'abstract' the SQL, and will look into implementing the repository pattern once I get around to refactoring a bunch of stuff. Currently all the database interactions are done either in the resolvers or services, but that definitely has to move into its own layer.

Thanks for the comment! I'll close this issue for now, and will open new ones once more concrete changes can be made.
